name: My source workflow

on:
  push:
    

jobs:     
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
      
    - name: Checkout release.txt
      uses: actions/checkout@v4
      with:
        repository: AruNiv/My_Target
        token: ${{ secrets.MyToken }}
        path: ./My_Target      
    
    - name: Update new_release.txt
      run: |
          bash find_replace.sh
          
    - name: Push the changes
      uses: EndBug/add-and-commit@v7
      with:
        cwd: ./My_Target
        message: 'update the version'
        branch: main 
