name: My source workflow

on:
  push:
    branches : [ main ]

jobs:     
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: trigger the Parent pom
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: AruNiv
        repo: My_Target
        github_token: ${{ secrets.Token }}

        workflow_file_name: main_target.yml
        ref: main
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: false

   
    - uses: actions/checkout@v1
    - name: Update file
      run: |
        sed -i 's/3.2.10/V3.0.0/' AruNiv/My_Target/release.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "version-update"
        git push

    - name: Test Modify
      uses: actions/checkout@v2.3.2
      with:
        file-path: AruNiv/My_Target/release.txt
        commit-msg: Update release.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
  
