name: My source workflow

on:
  push:
    branches : [ main ]

jobs:     
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: trigger the Parent pom
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: AruNiv
        repo: My_Target
        github_token: ${{ secrets.Token }}

        workflow_file_name: main_target.yml
        ref: main
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: false

    - name: Checkout release.txt
      uses: actions/checkout@v2
      with:
          repository: AruNiv/My_Target
          token: ${{ secrets.Token }}
          path: ./release.txt

    - name: Update release.txt
      run: |
          sed -i 's/3.2.10/V3.0.0/g' ./release.txt
          
    - name: Push the changes
      uses: EndBug/add-and-commit@v7
      with:
          cwd: ./release.txt
          message: 'update the version'
          branch: master

