name: My source workflow

on:
  push:
    branches : [ main ]

jobs:     
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release.txt
      uses: actions/checkout@v2.4.0
      with:
        repository: AruNiv/My_Target
        token: ${{ secrets.MyToken }}
        path: ./My_Target
        sparse-checkout: |
                  release.txt
        sparse-checkout-cone-mode: false

    - name: Update release.txt
      run: |
          sed -i 's/Version=3.0.0/Version=V4.0.0/g' ./My_Target/release.txt
          
    - name: Push the changes
      uses: EndBug/add-and-commit@v7
      with:
        cwd: ./My_Target
        message: 'update the version'
        branch: main 
