name: My source workflow

on:
  push:
    branches : [ main ]

jobs:     
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: trigger the Parent pom
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: AruNiv
        repo: My_Target
        github_token: ${{ secrets.MyToken }}

        workflow_file_name: main_target.yml
        ref: main
        wait_interval: 10
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: false

    - name: Checkout release.txt
      uses: actions/checkout@v4.0
      with:
        repository: AruNiv/My_Target
        token: ${{ secrets.MyToken }}
        path: ./My_Target

    - name: Update release.txt
      run: |
          sed -i 's/Version=3.0.0/Version=V4.0.0/g' ./My_Target/release.txt
          
    - name: Push the changes
      uses: EndBug/add-and-commit@v7
      with:
        cwd: ./My_Target
        message: 'update the version'
        branch: main 
