name: Release

on:
  push:
  
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install --save-exact
      
      - run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}  
                
      - name: Push the changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'update the version'
          branch: main       

      - name: Checkout release.txt
        uses: actions/checkout@v2.4.0
        with:
          repository: AruNiv/My_Target
          token: ${{ secrets.MYTOKEN }}
          path: ./My_Target
     
      - name: Update release.txt
        run: |
            grep ':' release.txt > ./My_Target/release.txt
            echo "##[set-env name=message;]${{grep ':' release.txt}}"
          
      - name: Push the changes
        uses: EndBug/add-and-commit@v7
        with:
          cwd: ./My_Target
          message: ${{ env.message }}
          branch: main 
