name: Release

on:
  push:
  
env: 
  version: "3.0.0"

  
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - run: npm install --save-exact
      - run: npm ci
      - run: npm install --save-dev @semantic-release/exec
     
      - run:
          (npx semantic-release --dryRun | grep -oP 'Published release \K.*? ') >> release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     
     
      - name: Push the changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'update the version'
          branch: main 
          
      
        
